### ISSUE TITLE
Do you mind if I update the tests to mocha?

### ISSUE THREAD

**Issue by mansona** [JoshKaufman/ursa#108]
Hey Folks, 

I was going to spend some time updating the testing system for this repo to mocha but I thought I should ask first ;) 

I was looking at the travis output for this PR https://github.com/quartzjer/ursa/pull/107 and I noticed that it didn't show a list of the tests that passed, instead it just says "All tests pass!" in the Travis output. If you have a look at one of my other modules and compare the Travis output https://travis-ci.org/Blooie/express-autoroute/jobs/74972233

Like i said, I would love to update the tests but I didn't want to just land a PR without asking first :wink:

**Comment by quartzjer** [comment]
I would definitely love that, I doubt anyone would complain about having better test output :)

:+1:

**Comment by mansona** [comment]
:joy: great, i'll take a look this week some time. :+1:
